package com.acme.longlife.domain.model;

import com.acme.longlife.domain.model.BigTree;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.context.annotation.Bean;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import java.util.Calendar;
import java.util.Date;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.when;

@ExtendWith(SpringExtension.class)
public class BigTreeTest {
    @Autowired
    BigTree bigTree;

    @TestConfiguration
    static class BigTreeTestConfiguration{
        @Bean
        public BigTree bigTree(){
            return new BigTree()
                    .setId(1L)
                    .setUsername("usuario1")
                    .setEmail("usuario@correo.com")
                    .setFirstName("Sancho")
                    .setLastName("Panza")
                    .setGender("M");
        }
    }

    @Test
    public void whenGetIdThenReturnsId(){
        //Arrange
        //BigTree is autogenerated

        //Act
        Long id = bigTree.getId();

        //Assert
        assertThat(id).isEqualTo(1L);
    }
}
